function g03_DemoButton
f = figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Ejemplo GUI',...
    'Position',[0 0 300 200]);
centerfig(f);

uicontrol('style','push',... 
    'String','Botón',... 
    'Units','Normalized',... 
    'Position',[0.3 0.40 0.40 0.2],...
    'FontSize',14,...
    'FontWeight','bold',...
    'ForegroundColor',rand(1,3),...
    'Callback',@bt_callback);

% Función que define la respuesta al presionar el botón.
    function bt_callback(src,~)
        % Modifica el color de fondo ('BackgroundColor') y el color
        % de fuente ('ForegroundColor') del Push Button.
        set(src,'BackG',rand(1,3),...
            'Foreground',rand(1,3));
        % Muestra un mensaje en el Command Window
        disp('Has presionado el botón');
    end
end