function g04_DemoEditText
f = figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Demo Edit Text',...
    'Position',[0 0 300 200]);
centerfig(f);

uicontrol('style','edit',...
    'String','Puede borrar esto',...
    'Units','Normalized',...
    'Position',[0.1 0.40 0.8 0.2],...
    'FontSize',14,...
    'FontWeight','bold',...
    'FontName','DejaVu Sans Mono'); % Tipo de fuente

end