function g07_DemoListBox
f = figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Ejemplo GUI',...
    'Position',[0 0 300 200]);
centerfig(f);

lista = {'Perro','Gato','Tigre','León'};
uicontrol('style','listbox',...
    'String',lista,...
    'Units','Normalized',...
    'Position',[0.1 0.1 0.8 0.8],...
    'FontSize',12,...
    'Callback',@select_fcn);

% 
    function select_fcn(src,~)
        all_str = get(src,'String');
        k = get(src,'Value');
        msgbox(['Has presionado: ',all_str{k}]);
    end
end