function g09_DemoCheckBox
f = figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Ejemplo GUI',...
    'Position',[0 0 300 200]);
centerfig(f);

uicontrol('style','checkbox',...
    'String','Ventana redimensionable',...
    'Callback',@check_callback,...
    'Units','Normalized',...
    'Position',[0.1 0.4 0.8 0.2],...
    'FontSize',12);

    function check_callback(src,~)
        estado = get(src,'Value');
        if estado
            set(f,'Resize','on');
        else
            set(f,'Resize','off');
        end
    end
end