function g13_IntegraDeriva
f = figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Integra - Deriva',...
    'Position',[0 0 300 200],...
    'Resize','off');
centerfig(f);

uicontrol('style','text',...
    'String','  f(x)  ',....
    'Position',[10 160 60 20],...
    'FontSize',10);
hFun = uicontrol('style','edit',...
    'String','',....
    'Position',[80 160 200 20],...
    'FontSize',10);

uicontrol('style','text',...
    'String','Derivada',...
    'Position',[10 120 60 20]);
hDer = uicontrol('style','edit',...
    'String','',....
    'Position',[80 120 200 20],...
    'FontSize',10,...
    'Enable','off'); % No editable

uicontrol('style','text',...
    'String','Integral',...
    'Position',[10 80 60 20]);
hInt = uicontrol('style','edit',...
    'String','',....
    'Position',[80 80 200 20],...
    'FontSize',10,...
    'Enable','off'); % No editable

% Etiquetas estáticas del mismo color que la ventana
set(findobj('style','text'),'BackG',get(f,'Color'));

uicontrol('style','push',...
    'String','Calcular',...
    'Position',[100 20 100 25],...
    'Callback',@calcular_fcn,...
    'FontSize',12);

    function calcular_fcn(~,~)
        % Convierte a tipo simbólico el 'String' obtenido del
        % Edit Text con referencia hFun
        f = sym(get(hFun,'String'));
        derivada = diff(f); % Deriva la función original
        integral = int(f); % Integra " " "
        % Posiciona los resultados obtenidos en los campos de texto
        % correspondientes. Es importante hacer la conversión explícita
        % de tipo sym a tipo char, tal como se indica.
        set(hDer,'String',char(derivada));
        set(hInt,'String',char(integral));
    end
end