function ex1
figure('MenuBar','none','NumberTitle','off',...
    'Name','GUI 1','Resize','off',...
    'Position',[200 200 250 150]);
centerfig(); % Centra la GUI en la pantalla
             % también puede usarse movegui('center')

uicontrol('style','text','String','MATLAB GUIs',...
    'Position',[30 100 190 20],'FontSize',12,...
    'FontWeight','bold','FontName','Courier',...
    'ForegroundColor','red');
end