function ex2
figure('MenuBar','none','NumberTitle','off',...
    'Name','GUI 2','Resize','off',...
    'Position',[0 0 200 100]);
centerfig();

uicontrol('style','push','String','Cambiar color',...
    'Position',[60 40 80 20],...
    'Callback','set(gcf,''color'',rand(1,3))');
end