function ex3 
figure('MenuBar','none','NumberTitle','off',...
    'Name','GUI 3','Resize','off',...
    'Position',[0 0 200 150]);
centerfig();

hedit=uicontrol('style','edit','String','',...
    'Position',[30 115 140 20]);

hstat=uicontrol('style','text','String','',...
    'Position',[30 75 140 20],...
    'BackgroundColor',[0.5 0.8 0.7]);

uicontrol('style','push','String','Mostrar',...
    'Position',[60 25 80 20],...
    'Callback',@func,'FontWeight','b');

    function func(src,event)
        texto=get(hedit,'str');
        set(hstat,'str',texto);
    end
end