function miniCommand
figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Mini C',...
    'Resize','off',...
    'Position',[200 200 300 200]);
centerfig;

ent=uicontrol('style','edit',...
    'String','',...
    'Position',[80 150 210 40],...
    'Horizontal','left',...
    'FontName','Courier New');
uicontrol('style','push',...
    'String','Evaluar',...
    'Position',[5 150 70 40],...
    'Callback',@evaluar);
sal=uicontrol('style','text',...
    'String','',...
    'Position',[80 20 210 110]);

    function evaluar(src,event)
        figure();
        inst=get(ent,'String');
        set(sal,'String',eval(inst));
    end

end