function MIAM_v1

figure('MenuBar','none',...
    'NumberTitle','off',...
    'Name','Programación en MATLAB - v1.0',...
    'Resize','off',...
    'Color','w',...
    'Position',[200 200 300 350]);
centerfig;

ax = axes('pos',[0 0 1 1],'visible','off');

movIni();

txtCap={'Capítulo 1. Introducción a MATLAB',...
    'Capítulo 2. Matrices y vectores',...
    'Capítulo 3. Cell arrays y estructuras',...
    'Capítulo 4. Gráficas',...
    'Capítulo 5. Matemáticas con MATLAB',...
    'Capítulo 6. Exportar e importar datos',...
    'Capítulo 7. Animaciones',...
    'Capítulo 8. Procesamiento de imágenes',...
    'Capítulo 9. Introducción a las GUIs MATLAB',...
    'Capítulo 10. Programación orientada a objetos'};

uicontrol('style','text',...
    'String','Programación en MATLAB',...
    'Position',[0 300 300 25],...
    'BackgroundColor','w',...
    'FontWeight','b',...
    'FontSize',10);
uicontrol('style','text',...
    'String','Autor: Jorge De Los Santos',...
    'Position',[0 270 300 25],...
    'BackgroundColor','w',...
    'FontWeight','b',...
    'FontSize',8);

iniP=230;
uicontrol('style','push',...
    'String',txtCap{1},...
    'Position',[0 iniP 300 25],...
    'Tag','bmenu',...
    'Callback','web(''data/cps/cp1/html/prueba.html'')');

uicontrol('style','push',...
    'String',txtCap{2},...
    'Position',[0 iniP-25 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{3},...
    'Position',[0 iniP-50 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{4},...
    'Position',[0 iniP-75 300 25],...
    'Tag','bmenu',...
    'Callback','web(''data/cps/cp4/html/C4_Graficas.html'')');

uicontrol('style','push',...
    'String',txtCap{5},...
    'Position',[0 iniP-100 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{6},...
    'Position',[0 iniP-125 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{7},...
    'Position',[0 iniP-150 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{8},...
    'Position',[0 iniP-175 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{9},...
    'Position',[0 iniP-200 300 25],...
    'Tag','bmenu');

uicontrol('style','push',...
    'String',txtCap{10},...
    'Position',[0 iniP-225 300 25],...
    'Tag','bmenu');

set(findobj('Tag','bmenu'),'BackgroundColor',[0.1 0.1 0.7],...
    'ForegroundColor','w','FontSize',9,...
    'HorizontalAlignment','left');

    function movIni()
        set(findobj('Tag','bmenu'),'visible','off');
        IMG=load('data\imag\imgs.mat');
        img=IMG.logoMATLAB;
        img=imresize(img,[350 300]);
        for i=1:100
            surf(membrane);
            axis off
            colormap(jet(randi([10 20 ])));
%             imshow(img+i);
            pause(0.01);
        end
        cla;
    end

end