function circularprogress
ANCHO = 200;
ALTO = 100;
hF = figure('MenuBar','None',...
    'NumberTitle','off',...
    'Name','ProgressBar',...
    'Resize','off',...
    'Color','w',...
    'Position',[0 0 ANCHO ALTO]);
centerfig(hF);

ax = axes('Position',[((1-(ALTO/ANCHO))/2)*1.2 0.1 (ALTO/ANCHO)*0.8 0.8]);

t = linspace(2*pi,0,13);
x = cos(t);
y = sin(t);
xx = 0.5*cos(linspace(0,2*pi));
yy = 0.5*sin(linspace(0,2*pi));
h = plot(ax,x,y,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',12,...
    'MarkerFaceColor',[0.1 0.1 0.5],...
    'MarkerEdgeColor',[0.1 0.1 0.5]);
set(ax,'Visible','off','NextPlot','add');
%h1 = fill(xx,yy,[0 0 0.5],'Parent',ax,...
%    'EdgeColor',[0 0 0.5],'EdgeAlpha',0.5,...
%   'FaceAlpha',0.5);

k = 1;
while ishandle(hF)
    ch = plot(ax,x(k:k+2),y(k:k+2),...
        'LineStyle','none',...
        'Marker','o',...
        'MarkerFaceColor',[0.3 0.3 0.9],...
        'MarkerEdgeColor',[0.3 0.3 0.9],...
        'MarkerSize',16);
    pause(0.05);
    if ishandle(ch),delete(ch),end;
    k = k + 1;
    if k==length(t)-2, k = 1; end;
end
% end
