function figresultados(resultados,nl)
cfondo=[1 1 1];
f = figure('Visible','on','MenuBar','none','resize','off','NumberTitle','off'...
    ,'Name','MFITEC - Resultados','position',[100,100,200,75+nl*25],'color',cfondo);
centerfig(f);

uicontrol('style','text','String','DATOS DE SALIDA','position',[10 75+(nl*25)-25 180 20],...
    'fontweight','bold','fontsize',9,'foregroundcolor',[0 0.5 0],...
    'backgroundcolor',cfondo);

uicontrol('style','text','String',resultados,'position',[10 10 180 25+nl*25],...
    'fontsize',10,'fontweight','normal','HorizontalAlignment','left',...
    'fontname','Cambria','backgroundcolor',cfondo);

end