function iniQ
figure('MenuBar','none',...
    'NumberTitle','off',...
    'resize','off',...
    'Name','Inicio >>',...
    'Position',[200 200 200 200]);
centerfig(gcf);

uicontrol('style','push',...
    'String','Crear cuestionario',...
    'FontWeight','b',...
    'Position',[10 170 140 25],...
    'BackgroundColor',[0.8 0.8 0.5],...
    'Callback',@nuevoQFcn);

uicontrol('style','push',...
    'String','Resolver cuestionario',...
    'FontWeight','b',...
    'Position',[10 140 140 25],...
    'BackgroundColor',[0.8 0.8 0.5],...
    'Callback',@resolverQFcn);

uicontrol('style','push',...
    'String','Ver cuestionarios',...
    'FontWeight','b',...
    'BackgroundColor',[0.8 0.8 0.5],...
    'Position',[10 110 140 25],...
    'Callback',@verQFcn);


    function nuevoQFcn(src,event)
        
    end

    function resolverQFcn(src,event)
        
    end

    function verQFcn(src,event)
        
    end

end