function mostrarPreg(pregunta,opciones)
pregunta='Responde esto';
opciones={'Opción 1','Opción 2','Opción 3','Opción 4'};

figure('MenuBar','none',...
    'NumberTitle','off',...
    'resize','off',...
    'Name','Question',...
    'Position',[200 200 300 250]);
centerfig(gcf);

uicontrol('style','text',...
    'String',['>> ',pregunta],...
    'FontWeight','b',...
    'ForegroundColor','b',...
    'Position',[10 170 280 70]);

bg=uibuttongroup('units','pixels',...
    'Position',[10 40 280 120]);

uicontrol(bg,'style','radio',...
    'String',opciones{1},...
    'Position',[10 90 100 20]);
    
uicontrol(bg,'style','radio',...
    'String',opciones{2},...
    'Position',[10 65 100 20]);

uicontrol(bg,'style','radio',...
    'String',opciones{3},...
    'Position',[10 40 100 20]);

uicontrol(bg,'style','radio',...
    'String',opciones{4},...
    'Position',[10 15 100 20]);

uicontrol('style','push',...
    'String','Listo',...
    'FontSize',10,...
    'FontWeight','b',...
    'Position',[125 10 50 20]);


end