function nuevoQ
clearvars('-global');
% prompt = {'Asignatura','Evaluador'};
% titulo = 'Datos generales';
% numlin = 1;
% def = {'Matemáticas','Jorge De Los Santos'};
% DG = inputdlg(prompt,titulo,numlin,def);
%
% arch=strcat('db/',DG{1},'.mat');

figure('MenuBar','none',...
    'NumberTitle','off',...
    'resize','off',...
    'Name','Nuevo >>',...
    'Position',[200 200 200 200]);
centerfig(gcf);

p1=uipanel(gcf,'units','pixels',...
    'Position',[10 90 180 100]);

p2=uipanel(gcf,'units','pixels',...
    'Position',[10 10 180 70]);

uicontrol(p1,'style','push',...
    'String','Agregar pregunta',...
    'BackgroundColor',[0.5 0.95 0.88],...
    'FontSize',10,'FontWeight','b',...
    'Position',[20 60 140 25],...
    'Callback',@agregarFcn);

uicontrol(p1,'style','push',...
    'String','Guardar todo',...
    'BackgroundColor',[0.5 0.95 0.88],...
    'FontSize',10,'FontWeight','b',...
    'Position',[20 30 140 25],...
    'Callback',@guardarFcn);

uicontrol(p2,'style','text',...
    'String','Preguntas agregadas',...
    'Position',[20 40 140 20]);

cAg=uicontrol(p2,'style','text',...
    'String','',...
    'FontSize',16,'FontWeight','b',...
    'ForegroundColor','b',...
    'BackgroundColor',[0.75 0.9 0.65],...
    'Position',[40 10 100 30]);


    function agregarFcn(src,event)
        global cont
        prompt = {'Pregunta','Opción A','Opción B','Opción C','Opción D'};
        titulo = 'Preguntas';
        numlin = [4,1,1,1,1];
        def = {'','','','',''};
        DG = inputdlg(prompt,titulo,numlin,def);
        
        if isempty(cont)
            cont=1;
        else
            cont=cont+1;
        end
        
        set(cAg,'str',cont);
    end

    function guardarFcn(src,event)
    end

end